<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <!-- Footer section for the Art Gallery website -->
    <footer class="footer">
        <div class="container">
            <div class="row">
                <!-- Column 1: About Us section -->
                <div class="col-md-4">
                    <h5>About Us</h5>
                    <p class="text-white">
                        Discover the world of art through our curated collection of masterpieces.
                        We bring you the best from classic and contemporary artists.
                    </p>
                </div>

                <!-- Column 2: Quick navigation links -->
                <div class="col-md-4">
                    <h5>Quick Links</h5>
                    <ul class="list-unstyled"> 
                        <li><a href="index.php" class="text-white">Home</a></li>
                        <li><a href="browse_artists.php" class="text-white">Artists</a></li>
                        <li><a href="browse_artworks.php" class="text-white">Artworks</a></li>
                        <li><a href="site_favorites.php" class="text-white">Favorites</a></li>
                    </ul>
                </div>

                <!-- Column 3: Social media links -->
                <div class="col-md-4">
                    <h5>Follow Us</h5>
                    <div>
                        <!-- Social media icons with external links -->
                        <a href="https://facebook.com" class="text-white me-3" aria-label="Facebook">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                        <a href="https://twitter.com" class="text-white me-3" aria-label="Twitter">
                            <i class="fab fa-twitter"></i>
                        </a>
                        <a href="https://instagram.com" class="text-white me-3" aria-label="Instagram">
                            <i class="fab fa-instagram"></i>
                        </a>
                        <a href="https://pinterest.com" class="text-white" aria-label="Pinterest">
                            <i class="fab fa-pinterest"></i>
                        </a>
                    </div>
                </div>
            </div>

            <!-- Footer bottom with dynamic copyright -->
            <div class="text-center pt-3 border-top">  
                <?php
                /**
                 * Display the current year dynamically.
                 *
                 * @var string $year Current year generated by PHP
                 */
                ?>
                <p class="text-white">&copy; <?php echo date("Y"); ?> Art Gallery. All rights reserved.</p>
            </div>
        </div>
    </footer>
</body>
</html>
